// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportGrid(arg1, arg2) {
  return window['go']['main']['App']['ExportGrid'](arg1, arg2);
}

export function GenerateHexCommand(arg1) {
  return window['go']['main']['App']['GenerateHexCommand'](arg1);
}

export function ParseCSV(arg1) {
  return window['go']['main']['App']['ParseCSV'](arg1);
}

export function SendPattern(arg1) {
  return window['go']['main']['App']['SendPattern'](arg1);
}
