// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportGrid(arg1:string,arg2:Array<any>):Promise<void>;

export function GenerateHexCommand(arg1:Array<any>):Promise<string>;

export function ParseCSV(arg1:string):Promise<Array<any>>;

export function SendPattern(arg1:Array<any>):Promise<void>;
